apiVersion: apps/v1
kind: Deployment
metadata:
  name: ultrafactory-oee
spec:
  selector:
    matchLabels:
      app: ultrafactory-oee
  template:
    metadata:
      labels:
        app: ultrafactory-oee
    spec:
      containers:
        - name: ultrafactory-oee
          image: lgustavopalmieri/ultrafactory-oee
          ports:
            - containerPort: 4003
---
apiVersion: v1
kind: Service
metadata:
  name: ultrafactory-oee
spec:
  selector:
    app: ultrafactory-oee
  ports:
    - port: 80
      targetPort: 4003
  type: LoadBalancer
