apiVersion: apps/v1
kind: Deployment
metadata:
  name: ultrafactory-oee
spec:
  selector:
    matchLabels:
      app: ultrafactory-oee
  template:
    metadata:
      labels:
        app: ultrafactory-oee
    spec:
      containers:
        - name: ultrafactory-oee
          # docker build -t lgustavopalmieri/ultrafactory-oee:v2 --push .
          image: lgustavopalmieri/ultrafactory-oee:v2
          ports:
            - containerPort: 4003
          envFrom:
            - secretRef:
                name: oee-ultrafactory-backend-secret
---
apiVersion: v1
kind: Service
metadata:
  name: ultrafactory-oee
spec:
  selector:
    app: ultrafactory-oee
  ports:
    - port: 80
      targetPort: 4003
  # type: LoadBalancer
# kubectl port-forward svc/ultrafactory-oee 4003:80