name: CI-CD
on:
  push:
    branches: ["feature/pipeline-ci"]
  workflow_dispatch:
jobs:
  CI:
    name: "CI job"
    runs-on: ubuntu-latest
    steps:
      - name: Obtendo o código
        uses: actions/checkout@4.1.5
      - name: Autenticação no Docker Hub
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
