name: second-pipeline
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  second-job:
    name: "Nodejs environment installing "
    runs-on: ubuntu-latest
    steps:
      - name: "Verify current nodejs version"
        run: node --version
      - name: "Nodejs 18.20.4 version definition"
        uses: actions/setup-node@v4
        with:
          node-version: "18.20.4"
      - name: "Verify nodejs version after installed"
        run: node --version
