name: CI-CD
on:
  push:
    branches: ["feature/pipeline-ci"]
  workflow_dispatch:
jobs:
  CI:
    name: "CI job"
    runs-on: ubuntu-latest
    steps:
      - name: Getting the code
        uses: actions/checkout@v4.1.5
      - name: DockerHub Authentication
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker Image Build and Push to DockerHub
        uses: docker/build-push-action@v5.3.0
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: |
            lgustavopalmieri/ultrafactory-oee:v${{ github.run_number }}  
            lgustavopalmieri/ultrafactory-oee:latest
  CD:
    name: "CD job"
    runs-on: ubuntu-latest
    needs: [CI]
    steps: 
    - name: Getting the code
      uses: actions/checkout@v4.1.5
    - name: Configuring Kubernetes context
    # Generic action used for any cloud provider
      uses: azure/k8s-set-context@v4.0.0
      with:
        method: kubeconfig
        # ADD from ~/.kube/config 
        kubeconfig: ${{ secrets.K8S_CONFIG }}
    - name: Execução do Manifesto
      uses: Azure/k8s-deploy@v5
      with:
        manifests: |
          ./k8s/deployment.yaml
        images: |
          lgustavopalmieri/ultrafactory-oee:v${{ github.run_number }}


# docker container run -d -p 4003:4003 lgustavopalmieri/ultrafactory-oee:v12
