name: second-pipeline
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  first-job:
    name: "first job"
    runs-on: ubuntu-latest
    steps:
      - name: "My first ACTION"
        run: echo "Hello World!"
  second-job:
    name: "Nodejs environment installing "
    runs-on: ubuntu-latest
    # this is how can we do sequential jobs
    needs: ["first-job"]
    steps:
      - name: "Verify current nodejs version"
        run: node --version
      - name: "Nodejs 18.20.4 version definition"
        uses: actions/setup-node@v4
        with:
          node-version: "20.13.1"
      - name: "Verify nodejs version after installed"
        run: node --version
